FROM base_ubuntu_python312_node20_mongodb7_240531

WORKDIR /work

COPY package.json /work/
COPY requirements.txt /work/

RUN npm install
RUN pip install -r requirements.txt

COPY watcher.js /work/
COPY admin_server.py /work/
COPY templates /work/templates
COPY run.sh /work/
RUN chmod +x run.sh

CMD ["/work/run.sh"]
