import React from 'react';
import ReactDOM from 'react-dom';
// import App from './App';
// import App from './CRUD-class/App';
import App from './CRUD-function/App';
// import App from './Life Cycle/FuncCycle';
// import App from './styled-components/App';
// import App from './Hooks/useClick';
// import App from './React-Ajax/AppLoading';
// import App from './Todo_functional/App';
// import App from './toy-project/App';
// import App from './React-Ajax/AppApis';
// import App from './toy-projects/redux-project/App';
// import App from './toy-projects/timer/App.refactoring';
// import App from './styled-components/Alignment';
// import App from './Hooks/useMemo';
// import App from './Hooks/useRef';
// import App from './experiment/useEffectVariable';
// import App from './recoil/practice/App';
// import App from './Hooks/useLayoutEffect';
// import App from './react-redux/App';
// import App from './app.js';

ReactDOM.render(<App />, document.getElementById('root'));
